# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(blank=True, max_length=140, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('instrument_value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('value_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'instruments_data',
                'managed': False,
            },
        ),
    ]
